### PR TITLE
Modify to use multi-stage builds

### PR DESCRIPTION
**Pull request by iiirischen**
@106303551 @jeff3071 再麻煩測試一下 image 的大小

### CODE REVIEW

**Comment by jeff3071** [comment]
建起來5.7G
但container有噴錯
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "poetry": executable file not found in $PATH: unknown`

是`polyhistor-backend-1`噴的

**Comment by jeff3071** [comment]
根據 https://stackoverflow.com/questions/78344145/buildx-build-platform-linux-amd64-significantly-increases-image-size-with-poet

把pyproject.toml改成
```
[tool.poetry]
name = "polyhistor"
version = "0.1.0"
description = ""
authors = ["jeff3071 <jeff563715@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.8"
langchain = "^0.1.13"
pymupdf = "^1.24.0"
tqdm = "^4.66.2"
markdown = "^3.6"
rank-bm25 = "^0.2.2"
pre-commit = "^3.7.0"
qdrant-client = "^1.9.0"
python-docx = "^1.1.2"
python-dotenv = "^1.0.1"
unstructured = "^0.13.7"
fastapi = "^0.111.0"
uvicorn = "^0.30.1"
torch = {url = "https://download.pytorch.org/whl/cpu-cxx11-abi/torch-2.2.2%2Bcpu.cxx11.abi-cp311-cp311-linux_x86_64.whl"}
sentence-transformers = "^3.0.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

接著dockerfile改成
```
FROM python:3.11.8-slim-bullseye as builder

WORKDIR /app

COPY pyproject.toml ./

ENV POETRY_VERSION=1.7.1 \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 

RUN pip install "poetry==$POETRY_VERSION"
RUN poetry install --no-interaction --no-ansi --verbose \
     && rm -rf $POETRY_CACHE_DIR
RUN poetry env use 3.11

COPY . .
FROM python:3.11.8-slim-bullseye
ENV POETRY_VIRTUALENVS_IN_PROJECT=true \
    PATH="/app/.venv/bin:$PATH"
COPY --from=builder /app /app

EXPOSE 8080

ENTRYPOINT ["uvicorn", "index:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
```

建出來的image會在1.4G左右

**Comment by iiirischen** [comment]
@jeff3071 我更新 pyproject 和 dockerfile了

**Comment by jeff3071** [comment]
OK

**Pull request merged**
