### PR TITLE
Feat/add qdrant

### PR DESCRIPTION
**Pull request by 106303551**
- 建立 qdrant 
- 串接 qdrant
- 導入測試資料至 qdrant

### CODE REVIEW

**Comment by jeff3071** [comment]
可能要先把.DS_Store刪掉?

**Comment by kt-cheng** [comment]
我在把 qdrant 用 docker 跑起來的時候有錯誤

`ERROR qdrant::startup: Panic occurred in file /qdrant/lib/collection/src/collection/mod.rs at line 177: Failed to parse stored collection version as semver: Error("unexpected character '\n' after patch version number")`

有人遇過一樣的訊息嗎？

**Comment by jeff3071** [comment]
同樣遇到

`ERROR qdrant::startup: Panic occurred in file /qdrant/lib/collection/src/collection/mod.rs at line 177: Failed to parse stored collection version as semver: Error("unexpected character '\n' after patch version number")`

**Comment by 106303551** [comment]
pre-commit 會去修改到 qdrant_storge 內相關的設定再push 導致無法運作 我再確認一下要怎麼調整

**Comment by 106303551** [comment]
有另外調整docker使用的方式，再麻煩幫忙測試，感謝～

**Comment by kt-cheng** [comment]
測試過可以正常運行了～

**Pull request merged**
